default:
    # To be processed by Ellis lanes
    path_month_raw:           "data-public/raw/month-performance.csv"
    intervention_start:       !expr as.Date("2019-11-01")

    path_log_flow:            !expr strftime(Sys.time(), "data-unshared/log/%Y/%Y-%m/flow-%Y-%m-%d--%H-%M-%S.log")
